
name: CI_CD_테스트

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    
jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: 01 checkOut
        uses: actions/checkout@v3
      - name: 02 use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 03 npm ci
        run: npm ci
      - name: 04 npm test의 문제점은?
        run: npm test

